### ISSUE TITLE
Is method "cube_int_atom" intended to calculate electron density? 

### ISSUE THREAD

**Issue by rogerwq** [funkymunkycool/Cube-Toolz#7]
Hey guys,

Thank you for sharing the code on handling cube file.

After a deep investigation, I found out that the code to calculate integral is theoretically wrong for calculating electron density. Maybe it was not used for that purpose. 

In my opinion, electron density should be calculated 
`nelectron += self.data[x][y][z] *self.data[x][y][z] * vol `

Beside, the 3 nested for-loop is too slow for walking the total mesh space. A preliminary filtering using atom center and radius could be applied to reduce the for-loop walking space and thus the exception time will be significantly shorter.

BR.

**Comment by funkymunkycool** [comment]
Hey,

The method doesn't calculate the electron density. It only takes the integral of whatever cube file you give it. It can be used on an electron density cube file and this will give you the total number of electrons. This should work properly, as it should simply be the integral in the code. I have tested it on a few electron density files and it works fine. 

If, however, you feed in a wavefunction, then you will indeed need to square the cube file before you calculate the integral. I believe there is a mult_cubes and square_cube function which would let you square the cube file before integration. 

Thanks for the nested for loop suggestion. It is indeed quite slow due to the nesting. I will put it on the todo list to come up with some preliminary screenings to increase the speed.

Cheers!
